// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV4rWWkyikTuUIMifX6wEh9p6f3OKD_Hs',
    appId: '1:617490770993:web:placeholder',
    messagingSenderId: '617490770993',
    projectId: 'rephrasely-c9a50',
    authDomain: 'rephrasely-c9a50.firebaseapp.com',
    storageBucket: 'rephrasely-c9a50.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV4rWWkyikTuUIMifX6wEh9p6f3OKD_Hs',
    appId: '1:617490770993:android:ab70ca079c74b9af69b910',
    messagingSenderId: '617490770993',
    projectId: 'rephrasely-c9a50',
    storageBucket: 'rephrasely-c9a50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV4rWWkyikTuUIMifX6wEh9p6f3OKD_Hs',
    appId: '1:617490770993:ios:placeholder',
    messagingSenderId: '617490770993',
    projectId: 'rephrasely-c9a50',
    storageBucket: 'rephrasely-c9a50.firebasestorage.app',
    iosBundleId: 'com.example.rephrasely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV4rWWkyikTuUIMifX6wEh9p6f3OKD_Hs',
    appId: '1:617490770993:ios:placeholder',
    messagingSenderId: '617490770993',
    projectId: 'rephrasely-c9a50',
    storageBucket: 'rephrasely-c9a50.firebasestorage.app',
    iosBundleId: 'com.example.rephrasely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV4rWWkyikTuUIMifX6wEh9p6f3OKD_Hs',
    appId: '1:617490770993:web:placeholder',
    messagingSenderId: '617490770993',
    projectId: 'rephrasely-c9a50',
    authDomain: 'rephrasely-c9a50.firebaseapp.com',
    storageBucket: 'rephrasely-c9a50.firebasestorage.app',
  );
}
